### PR TITLE
Standardize traits/actions:

### PR DESCRIPTION
**Pull request by jaklein**
name bold, folowed by colon

all separated by paragraphs

"Senses" is not a trait, has no colon

### CODE REVIEW

**Comment by maxrothman** [comment]
Wow! Thanks for the huge cleanup! It might take us a little time to review this, so hang tight.

**Comment by eepMoody** [comment]
Looked through all the changes, then built locally and spot-checked. All seems to be good!

:+1:

**Comment by maxrothman** [comment]
@jaklein it appears that this branch has conflicts with the master branch. Can you resolve those?

**Comment by maxrothman** [comment]
:+1: from me as well (once the conflicts are resolved)

**Comment by eepMoody** [comment]
@jaklein I'll take care of merging this in shortly, it looks like one of the changes we made since you submitted caused the conflicts. :)

**Comment by jaklein** [comment]
Thanks for merging, I have some more monster cleanup coming soon.

**Pull request merged**
