### PR TITLE
Monster's spell lists as lists + small bulette fix

### PR DESCRIPTION
**Pull request by snan**
So two separate things:
Monster's/NPC's spell lists are formatted in many ways across the various RST files. I want them to be all the same way. Blockquote (as some, not all, of the NPCs were), that's fine. Just as if they were any other special trait (as the monsters and a few of the NPCs were), that's a bit harder to work with but not impossible.
But I put them all in lists: none of the other monsters use lists and spell lists are just that, lists.
CSS will need to be tweaked perhaps.
Githubs RST preview doesn't show these nested lists so well, but they're there.

And the other thing was super minor, the Bulette had accidentally become line-quoted.

### CODE REVIEW

**Comment by maxrothman** [comment]
I'm 👍 on the bulette changes, but I'm not sure about the spell format changes. This would be diverging significantly from the PDF SRD format and it'd be less compact. On the other hand, if those changes actually improve readability, I'd be +1.

**Comment by maxrothman** [comment]
Looks like the nested lists aren't being rendered properly. This is the HTML that comes out:
```
<ul class="simple">
<li>Cantrips (at will):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/m/mage-hand.html#srd-mage-hand"><span>Mage Hand</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/p/prestidigitation.html#srd-prestidigitation"><span>Prestidigitation</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/r/ray-of-frost.html#srd-ray-of-frost"><span>Ray of Frost</span></a></li>
<li>1st level (4 slots):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/detect-magic.html#srd-detect-magic"><span>Detect Magic</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/m/magic-missile.html#srd-magic-missile"><span>Magic Missile</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/s/shield.html#srd-shield"><span>Shield</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/t/thunderwave.html#srd-thunderwave"><span>Thunderwave</span></a></li>
<li>2nd level (3 slots):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/a/acid-arrow.html#srd-acid-arrow"><span>Acid Arrow</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/detect-thoughts.html#srd-detect-thoughts"><span>Detect Thoughts</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/i/invisibility.html#srd-invisibility"><span>Invisibility</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/m/mirror-image.html#srd-mirror-image"><span>Mirror Image</span></a></li>
<li>3rd level (3 slots):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/a/animate-dead.html#srd-animate-dead"><span>Animate Dead</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/c/counterspell.html#srd-counterspell"><span>Counterspell</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/dispel-magic.html#srd-dispel-magic"><span>Dispel Magic</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/f/fireball.html#srd-fireball"><span>Fireball</span></a></li>
<li>4th level (3 slots):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/b/blight.html#srd-blight"><span>Blight</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/dimension-door.html#srd-dimension-door"><span>Dimension Door</span></a></li>
<li>5th level (3 slots):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/c/cloudkill.html#srd-cloudkill"><span>Cloudkill</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/s/scrying.html#srd-scrying"><span>Scrying</span></a></li>
<li>6th level (1 slot):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/disintegrate.html#srd-disintegrate"><span>Disintegrate</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/g/globe-of-invulnerability.html#srd-globe-of-invulnerability"><span>Globe of Invulnerability</span></a></li>
<li>7th level (1 slot):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/f/finger-of-death.html#srd-finger-of-death"><span>Finger of Death</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/p/plane-shift.html#srd-plane-shift"><span>Plane Shift</span></a></li>
<li>8th level (1 slot):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/d/dominate-monster.html#srd-dominate-monster"><span>Dominate Monster</span></a>
- <a class="reference internal" href="../../../spellcasting/spells_a-z/p/power-word-stun.html#srd-power-word-stun"><span>Power Word Stun</span></a></li>
<li>9th level (1 slot):
- <a class="reference internal" href="../../../spellcasting/spells_a-z/p/power-word-kill.html#srd-power-word-kill"><span>Power Word Kill</span></a></li>
</ul>
```

**Comment by snan** [comment]
Is this a Sphinx/python issue?
Github's RST engine shows the same thing but locally (with pandoc) I could get it to nest properly. (I couldn't before I added a newline before every spell level header; perhaps Sphinx's RST need newlines after them, too?)

Nested lists can be styled via CSS to mirror any one of the two previous looks (blockquoted and not blockquoted) that you were using. But of course all patches and pulls are optional, it's just that I needed the spell lists to be regular

**Comment by maxrothman** [comment]
TBH I think it's an issue in the github RST engine. Docutils (the engine Sphinx uses) is the reference implementation for RST.

**Comment by snan** [comment]
Thanks for clarifying that. I still don't have sphinx installed, but now I atleast have docutils installed. (I was using Pandoc.)

**Comment by maxrothman** [comment]
Cool, I'll build and test this weekend.

**Comment by eepMoody** [comment]
Het @snan I'm trying to get this project moving again, and that includes going back and merging in all this stuff I've let sit for _far_ too long. 

I did a local check and all appears to be good, if you want to just merge from master I'll get this merged in right away (Github won't let me do it on this PR for some reason)

**Comment by snan** [comment]
OK, I've hit the "Update branch" button. Let me know if that isn't enough.

I use Open5e all the time

**Comment by eepMoody** [comment]
That seems to have done it! Glad to hear you're still enjoying the site.

**Pull request merged**
