### PR TITLE
Fixing some damage/condition immunities.

### PR DESCRIPTION
**Pull request by BrianWendt**
Moving conditions into `condition_immunities` from `damage_immunities`.

### CODE REVIEW

**Comment by BrianWendt** [comment]
I found these while working on this: https://raw.githubusercontent.com/BrianWendt/dnd5e_json_schema/master/srd/monsters.json

**Comment by augustjohnson** [comment]
That's pretty cool!  Definitely deeper in detail than our set, but
generally the same thing.

https://github.com/theoperatore/dnd-monster-api is where a lot of the data
came from.

Should we try and get everyone together and make one DND5e API to rule them
all?

**Comment by BrianWendt** [comment]
I built `srd/monsters.json` using your open5e dataset for monsters. It's the most complete I've found so far (that was strictly SRD).

I just parsed some of the fields further to give anyone implementing more flexibility with how they present and use the data. I'm going to be moving my [DnDEM](https://github.com/BrianWendt/dndem) project to SRD data only with the option of importing in "user created" content. Keep Wizards happy.

I'd be interested in working with eepMoody/open5e to finish a completed schema draft and convert all of the data over to it.

**Comment by augustjohnson** [comment]
Glad to hear!  I put a bunch of work into it!

Just for some context, there's a couple of different json representations
of monsters, even within Open5e... I believe the /data folder contains the
ones that the frontend app runs off of, but they vary slightly from the
ones that the API presents (look for movement speeds, I think that's a
difference).

Join the dev-corner on the Open5e discord if you haven't already!
https://discord.gg/bSsNgyv

August

**Pull request merged**
